@echo off
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py
python borrar.py